### ISSUE TITLE
HTMLHinter stays highlighted when there are two errors and they're both fixed.

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#130]
STR:
- Load default page
- Remove the > from the meta tag
- Remove the > from the title tag
- Add the > back to the meta tag to fix the error
- Add the > back to the title tag to fix the error

No errors show in the console.

**Comment by KeniMorri** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1750230/6758502/09a61e40-cf0f-11e4-938f-875d8616acd0.gif)

You mean this?

**Comment by humphd** [comment]
This was fixed by @gideonthomas recently, but I don't know if it landed.  It's a dupe of #127.

**Comment by AJDBenner** [comment]
@humphd it looks like this issue still happens after @gideonthomas patch.

**Comment by AJDBenner** [comment]
My fault, @gideonthomas patch does fix this
