### ISSUE TITLE
I can create a dir called "../things" and it does hilarious things

### ISSUE THREAD

**Issue by Pomax** [humphd/brackets#434]
I accidentally clicked "new folder" inside one of my project folders, so for the heck of it I figured "let's call it ../extensions and see if that makes it one dir up". That's.... not what it did.

![screenshot 82](https://cloud.githubusercontent.com/assets/177243/9372501/1a83a41a-4694-11e5-806a-83b65455868a.png)

**Comment by humphd** [comment]
Filed upstream, this is a Brackets bug.

**Comment by Pomax** [comment]
what's the issue #? it's a very cool bug =P

**Comment by humphd** [comment]
@simon66 this is the bug I was talking about, along with associated bug filed in Brackets upstream.

**Comment by simon66** [comment]
Thanks @humphd! Yea I was talking to @gideonthomas about this on Friday.

Mind if I tackle this bug?

Here's more on this bug:

![screen shot 2017-02-11 at 4 09 13 pm](https://cloud.githubusercontent.com/assets/1103528/22857521/a89f6334-f074-11e6-88eb-d9dde6094114.png)

By using relative path, I was able to "hop" between directories.
Create/rename a folder and name it `../../../test`, if `test` folder already exist, just name it to something else.

**Comment by Pomax** [comment]
Note that supposedly this is fixed in Brackets itself, so the fix here *might* be "uplift brackets to 1.8" here

**Comment by gideonthomas** [comment]
@simon66 are you interested in testing that out? See if you can reproduce this in Brackets 1.4 and 1.8. If this bug is not in 1.8, we should just merge with 1.8 (or if this is urgent, cherry-pick their fix for this into our repo).

**Comment by simon66** [comment]
Hi @gideonthomas 
Bug still exists in Brackets 1.8

![screen shot 2017-02-12 at 12 30 43 pm](https://cloud.githubusercontent.com/assets/1103528/22864438/6fca3ea2-f11f-11e6-9352-e418e0d8a327.png)
![screen shot 2017-02-12 at 12 31 40 pm](https://cloud.githubusercontent.com/assets/1103528/22864441/738c37b6-f11f-11e6-964b-7055c4e4ea97.png)
 As you can see, one file is placed in the "Root" folder and the other in the "Contents" folder.

**Comment by Pomax** [comment]
Then step one is going to filing an issue over on the brackets repository to tell them this can be done, probably with a mention of https://github.com/adobe/brackets/issues/11609 (which is where we originally filed it, and got closed by a PR that was intended to address this issue.
