### ISSUE TITLE
Images won't load if they have focus when Bramble starts

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#494]
STR:
* drag and drop an image into your filesystem
* select the image in the file tree
* refresh the page
* notice the image is a 404
* select the index.html
* reload the page
* select the image from the file tree
* notice it works fine when not selected on startup

![screenshot 2015-11-02 15 13 08](https://cloud.githubusercontent.com/assets/427398/10893069/cd35db9e-8174-11e5-9957-eccd1d26c042.png)

**Comment by humphd** [comment]
This is only an issue in Bramble vs. Thimble, it seems, because in Thimble we always try to load an HTML file.

**Comment by humphd** [comment]
Please test my PR in https://github.com/mozilla/brackets/pull/625 with this bug, I might have fixed it when I rewrote that code.

**Comment by peiying16** [comment]
I want to test it. I use following commands to download your branch, where are the codes it downloads to?
```
git remote add "humphd" https://github.com/humphd/brackets.git
git fetch humphd
```

**Comment by humphd** [comment]
```
git remote add humphd https://github.com/humphd/brackets.git
git fetch humphd
git checkout livedev-fixes
```

**Comment by peiying16** [comment]
I checkout to your branch, but I can't load the page. Error message is here.
![err](https://cloud.githubusercontent.com/assets/25106861/23874333/9596bd42-080b-11e7-9df9-01be45f1fb0f.PNG)

**Comment by peiying16** [comment]
Here are my branchs and remote
![git](https://cloud.githubusercontent.com/assets/25106861/23874609/b0cddf2c-080c-11e7-8ead-f9ab9da1ffab.PNG)

**Comment by humphd** [comment]
I would clear your cache.  Let's discuss in class tomorrow too.

**Comment by humphd** [comment]
@peiying16 thanks for altering me to this--it was a bug in my code.  I've pushed a new commit on my PR which fixes it.  Do you mind trying again?  Thanks for letting me know about this, I totally missed it!

**Comment by peiying16** [comment]
@humphd Hello, I try your PR. Now I can load the page successfully, but it doesn't fix this issue. It is still 404
![image](https://cloud.githubusercontent.com/assets/25106861/23972755/6fc8f496-09a9-11e7-80c3-27601683117e.png)

**Comment by humphd** [comment]
OK, this is helpful.  Thank you.  I think it's something to do with it trying to load an `ImageView` vs. an HTML Live Document on startup, and not using a rewritten Blob URL.  We'll have to debug this separate to what you're doing.

Thanks for you testing, I just hoped it would solve this bug, too.

**Comment by humphd** [comment]
NOTE: I have a fix for this in my work for #725, see https://github.com/mozilla/brackets/pull/725/commits/a122b49a16170be920610dd288273d2858cccfb6
